<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__username</name>
   <tag></tag>
   <elementGuidId>62a98ace-13e0-4690-b9de-d4344149ccc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dipo_login--35329_text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dipo_login--35329_text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dipo_login--35329_text</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ced6b808-b8ca-4681-82bb-799ce51163f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f19ef6fc-9476-4172-9289-79506201f1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>sendenter(event,'dipo_login-','dipo_login--35329','enter')</value>
      <webElementGuid>17fed899-ad29-4cc0-9e07-81b074722845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nikitasmartentry1 nikitasmartentry  </value>
      <webElementGuid>2f6d0196-53cb-4a11-a6ce-7a3c4556aaea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dipo_login--35329_text</value>
      <webElementGuid>333395ee-e092-4a18-b1cf-0e285999c9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dipo_login--35329_text&quot;)</value>
      <webElementGuid>ad5e6d4a-b59f-4a3f-936d-ff5e6fcc290b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dipo_login--35329_text']</value>
      <webElementGuid>e62bd10a-fbd1-48a6-8b6e-fbd418f45dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dipo_login--35329']/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>083ff240-6b4b-49fc-b61c-4be1443c9329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5fa921e1-5dfa-430b-9768-f02eece82ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dipo_login--35329_text']</value>
      <webElementGuid>2176101a-fa5f-44fd-ae9d-323e79435be3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
