<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__password</name>
   <tag></tag>
   <elementGuidId>dcfca46c-4ad3-4308-b542-30eea875e947</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dipo_login--35327_text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dipo_login--35327_text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dipo_login--35327_text</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1011ef6-7dbd-43b5-b787-c0daa5e8abbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ae60a291-705a-4673-a699-1aca9b234bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>sendenter(event,'dipo_login-','dipo_login--35327','enter')</value>
      <webElementGuid>7f360ced-5417-4553-8a91-6e96826f2268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nikitasmartentry1 nikitasmartentry  </value>
      <webElementGuid>d7be031a-6c64-429c-91a4-80d34e608f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dipo_login--35327_text</value>
      <webElementGuid>89033b56-675d-4304-b26b-d1673492aad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dipo_login--35327_text&quot;)</value>
      <webElementGuid>7ce7f5a9-8b8f-4056-baa2-1cb00b89d1d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dipo_login--35327_text']</value>
      <webElementGuid>c118a998-84f3-45c8-b1ad-9863b5751291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dipo_login--35327']/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>a7522312-f33d-40ff-8286-1c14faa97a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>cebee834-07f9-45be-92a2-1c4db4f29566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'dipo_login--35327_text']</value>
      <webElementGuid>5aff21f9-5fb6-4d12-aa31-4c6444be4ac2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
